<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: https://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_twentytwentyone_child_theme_01_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_twentytwentyone_child_theme_01_parent_style';
    $parent_base_dir = 'twentytwentyone';
    // Fonts
    wp_enqueue_style( 'font-awesome-style', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css');
    wp_enqueue_style( 'verveine_font', 'https://use.typekit.net/wbt5wou.css');

    // Lottie Animations
    wp_enqueue_script('scroll_magic_testing_script', 'https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js');

    //    slick
    wp_enqueue_script('slick_carousel', 'https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js', array('jquery'));
    wp_enqueue_style( 'slick_carousel_style', 'https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css');

    // ScrollMagic
    
    
    wp_enqueue_script('tween_max_script', 'https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js');
    wp_enqueue_script('scroll_magic_testing_script', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.js' );

    wp_enqueue_script('scroll_magic_script', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.js');
    wp_enqueue_script( 'scroll_magic_anim_script', 'https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/animation.gsap.js'  );
    wp_enqueue_script('velocityjs_script', 'https://cdnjs.cloudflare.com/ajax/libs/velocity/2.0.6/velocity.js' );
    
    


    // Styling
    wp_enqueue_style( 'bootstrap_style', 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css');


    // Custom
    wp_enqueue_script( 'gbc_main_script', get_stylesheet_directory_uri() . '/script.js', array('jquery'));

    wp_localize_script( 'gbc_main_script', 'my_ajax_object',
        array(
                'ajax_url' => admin_url( 'admin-ajax.php'),
                'customValue' => 'Hello',

     ) );

     wp_localize_script( 'gbc_main_script', 'gbc_animation_timing',
     array(
             'heading'      => get_field('heading_delay', 'option'),
             'subheading'   => get_field('subheading_delay', 'option'),
             'excerpt'      => get_field('excerpt_delay', 'option'),
             'sub_excerpt'  => get_field('secondary_excerpt_delay', 'option'),
             'fade_time'    => get_field('fade_in_time', 'option'),

  ) );

}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_twentytwentyone_child_theme_01_child_theme_enqueue_styles' );

function foo() {
    return 'bar';

}
add_action('wp_ajax_get_more_notable_past_events', 'get_more_notable_past_events' ); // executed when logged in
add_action('wp_ajax_nopriv_get_more_notable_past_events', 'get_more_notable_past_events' ); // executed when logged out



function enqueue_custom_scripts() {

    wp_enqueue_style(
        'child-theme-style',
        get_stylesheet_directory_uri() .'/style.css',
        array( 'bootstrap_style' )
    );

    wp_enqueue_style(
        'theme-update-styles',
        get_stylesheet_directory_uri() .'/assets/css/styles.css',
        array( 'child-theme-style' )
    );

    wp_enqueue_style(
        'services-style',
        get_stylesheet_directory_uri() .'/services-style.css',
        array( 'bootstrap_style' )
    );

    wp_enqueue_style(
        'timeline-style',
        get_stylesheet_directory_uri() .'/assets/css/timeline.css'
    );
}

add_action( 'wp_enqueue_scripts', 'enqueue_custom_scripts', PHP_INT_MAX);

function create_posttype() {
    register_post_type( 'Latest News',
        array(
            'labels' => array(
                'name' => __( 'Latest News' ),
                'singular_name' => __( 'Latest News' )
            ),
            'public' => true,
            'has_archive' => true,
            'rewrite' => array('slug' => 'latest-news'),
            'show_in_rest' => true,
            'supports' => array( 'title', 'editor', 'thumbnail' )
        )
    );

    register_post_type( 'Current Events',
        array(
            'labels' => array(
                'name' => __( 'Current Events' ),
                'singular_name' => __( 'Current Event' )
            ),
            'public' => true,
            'has_archive' => true,
            'rewrite' => array('slug' => 'current-events'),
            'show_in_rest' => true,
            'supports' => array( 'title', 'editor', 'thumbnail' )
        )
    );

    register_post_type( 'Past Events',
        array(
            'labels' => array(
                'name' => __( 'Past Events' ),
                'singular_name' => __( 'Past Event' )
            ),
            'public' => true,
            'has_archive' => true,
            'rewrite' => array('slug' => 'past-events'),
            'show_in_rest' => true,
            'supports' => array( 'title', 'editor', 'thumbnail' )
        )
    );

    register_post_type( 'Team Members',
        array(
            'labels' => array(
                'name' => __( 'Team Members' ),
                'singular_name' => __( 'Team Member' )
            ),
            'public' => true,
            'has_archive' => false,
            'rewrite' => array('slug' => 'team-members'),
            'show_in_rest' => true,
            'supports' => array( 'title', 'thumbnail', 'page-attributes' )
        )
    );
}
add_action( 'init', 'create_posttype' );

if( function_exists('acf_add_options_page') ) {

    acf_add_options_page(array(
        'page_title' 	=> 'Lester Brunt Options',
        'menu_title'	=> 'Lester Brunt Options',
        'menu_slug' 	=> 'option-settings',
        'capability'	=> 'edit_posts',
        'redirect'		=> false
    ));
}


function get_custom_posts($post_type){
    $args = array( 'post_type' => $post_type );
    $posts = get_posts($args);
    $count = 0;
    foreach( $posts as $post) : setup_postdata($post);
        $count++;
        if($count>3){break;}
        $img_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'full' )[0];
        ?>
        <div class="image-container" style="width: 420px; height: 420px; background-image: url('<?php echo $img_url; ?>'); "></div>
        <h4 class="topic"><?php the_field( 'topic', $post->ID ); ?></h4>
        <p class="gold article-title col-9"><?php echo $post->post_title; ?></p>
        <p class="gold article-date"><?php the_field( 'date', $post->ID ); ?></p>
        <hr class="gold divider-line">
        <div class="excerpt-container col-9">
            <p class="cello"><?php the_field( 'excerpt', $post->ID ); ?></p>
        </div>
        <a href="<?php echo get_post_permalink($post->ID); ?>" target="_blank">
            <button class="button-orange news-event-button scaled-button">Read More</button>
        </a>


        <?php
    endforeach;
}

function get_current_events($post_type){
    $args = array( 'post_type' => $post_type );
    $posts = get_posts($args);
    $count = 0;
    foreach( $posts as $post) : setup_postdata($post);
        $count++;
        if($count>3){break;}
        $img_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'full' )[0];
        ?>

        <div class="image-container" style="width: 420px; height: 420px; background-image: url('<?php echo $img_url; ?>'); "></div>
        <h4 class="topic"><?php the_field( 'client', $post->ID ); ?></h4>
        <p class="gold article-title col-9"><?php echo $post->post_title; ?></p>
        <p class="gold article-date"><?php the_field( 'date', $post->ID ); ?></p>
        <hr class="gold divider-line">
        <div class="excerpt-container col-9">
            <p class="cello"><?php the_field( 'excerpt', $post->ID ); ?></p>
        </div>
        <a href="<?php echo get_post_permalink($post->ID); ?>" target="_blank">
            <button class="button-orange news-event-button scaled-button">Read More</button>
        </a>


    <?php
    endforeach;
}


function get_notable_past_events($post_type){
    $args = array( 'post_type' => $post_type );
    $posts = get_posts($args);
    $count = 0;
    foreach( $posts as $post) : setup_postdata($post);
        $count++;
        if($count>2){break;}
        $img_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'full' )[0];
        ?>
    <div class="event col-5 offset-1" style="">
        <div class="image-container" style="width: 420px; height: 420px; background-image: url('<?php echo $img_url; ?>'); "></div>
        <h4 class="topic"><?php the_field( 'client', $post->ID ); ?></h4>
        <p class="gold article-title col-10"><?php echo $post->post_title; ?></p>
        <p class="gold article-date"><?php the_field( 'date', $post->ID ); ?></p>
        <hr class="gold divider-line">
        <div class="excerpt-container col-10">
            <p class="cello"><?php the_field( 'excerpt', $post->ID ); ?></p>
        </div>
        <a href="<?php echo get_post_permalink($post->ID); ?>" target="_blank">
            <button class="button-orange news-event-button scaled-button">Read More</button>
        </a>
    </div>

    <?php
    endforeach;
}

function get_more_notable_past_events(){
    $args = array( 'post_type' => 'Past Events' );
    $posts = get_posts($args);
    $count = 0;
    foreach( $posts as $post) : setup_postdata($post);
        $count++;
        if($count<2){continue;}
        $img_url = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'full' )[0];
        ?>
        <div class="event col-5 offset-1" style="">
            <div class="image-container" style="width: 420px; height: 420px; background-image: url('<?php echo $img_url; ?>'); "></div>
            <h4 class="topic"><?php the_field( 'client', $post->ID ); ?></h4>
            <p class="gold article-title col-10"><?php echo $post->post_title; ?></p>
            <p class="gold article-date"><?php the_field( 'date', $post->ID ); ?></p>
            <hr class="gold divider-line">
            <div class="excerpt-container col-10">
                <p class="cello"><?php the_field( 'excerpt', $post->ID ); ?></p>
            </div>
            <a href="<?php echo get_post_permalink($post->ID); ?>" target="_blank">
                <button class="button-orange news-event-button scaled-button">Read More</button>
            </a>
        </div>

    <?php
    endforeach;
}